---
- hosts: all
  tasks:
    - name: Installs nginx web server
      state: "present"
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx
    - name: Copiar Sitio SCBA desde Repositorio
      copy: src=/home/mariano/repositorio/wwwscba/www.scba.gov.ar  dest=/usr/share/nginx/html/ mode=0644
      
