---
- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present
  
  - name: If follow=yes, /path/to/file will be overwritten by contents of foo.conf
    copy:
      src: /home/ansible/repositorio/wwwscba/
      dest: /usr/share/nginx/html/  # link to /path/to/file
      remote_src=yes
      mode=preserve
        
  - name: Start NGiNX
    service:
      name: nginx
      state: started
