---
- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present
  
  - name: If follow=yes, /path/to/file will be overwritten by contents of foo.conf
    copy:
      src: 
      dest: /usr/share/nginx/html/index.html  # link to /path/to/file
      follow: yes
  
  - name: Start NGiNX
    service:
      name: nginx
      state: started
